services:
  catalog-db:
    image: postgres:16
    container_name: catalog-db
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    ports:
      - "5433:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  catalog-api:
    container_name: catalog-api
    build:
      context: ./services/catalog-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalogdb
      SPRING_DATASOURCE_USERNAME: catalog_user
      SPRING_DATASOURCE_PASSWORD: catalog_pass
    ports:
      - "8080:8080"
    depends_on:
      - catalog-db
      - kafka
      - eureka-server
      - config-server

  order-api:
    container_name: order-api
    build:
      context: ./services/order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass
    ports:
      - "8081:8081"
    depends_on:
      - order-db
      - catalog-api
      - kafka
      - eureka-server
      - config-server

  eureka-server:
    container_name: eureka-server
    build:
      context: ./services/eureka-server
    ports:
      - "8761:8761"

  config-server:
    container_name: config-server
    build:
      context: ./services/config-server
    environment:
      CONFIG_REPO_PATH: /config-repo
    volumes:
      - ./config-repo:/config-repo:ro
    ports:
      - "8888:8888"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:19092,CONTROLLER://kafka:19093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:19093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"

volumes:
  catalog-db-data:
  order-db-data:
