spring:
  application:
    name: catalog-api
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogdb
    username: catalog_user
    password: catalog_pass
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: catalog-service

server:
  port: 8080
